name = "codeDownload"
uuid = "ada0d3cd-545a-47f9-82e3-bbce5ed9b9ec"
authors = ["Martin Alfaro <50346244+alfaromartino@users.noreply.github.com>"]
version = "0.1.0"

[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
